# HOWTO install libcurlpp
# yaourt -S aur/libcurlpp

CXXFLAGS += -g -pthread
LDFLAGS += -g -lcurlpp -lcurl -lpugixml
curlpp_download_example : curlpp_download_example.cpp
clean:
	rm curlpp_download_example
